/**
 * Copyright (C) 2020 to the present, Crestron Electronics, Inc.
 * All rights reserved.
 * No part of this software may be reproduced in any form, machine
 * or natural, without the express written consent of Crestron Electronics.
 * Use of this source code is subject to the terms of the Crestron Software License Agreement 
 * under which you licensed this source code.  
 *
 * This code was automatically generated by Crestron's code generation tool.
*/

var versionInfoModule = (function () {
    'use strict';

    let outputValue = true;
    let appName = null;
    let appVersion = null;
    let errorClass = 'version-error';

    /**
     * Initialize Method
     */
    function onInit() {
        getAppVersionInfo();
        versionInformation();
    }

    /**
     * Fetch app version info from menifest file.
     */
    function getAppVersionInfo() {
        serviceModule.loadJSON('./../../assets/data/app.manifest.json', function (response) {
            response = JSON.parse(response);
            appName = response.appName;
            appVersion = response.appVersion;
            let _appVersionEl = document.getElementById('appVersion');
            if (!!appName && !!appVersion) {
                let _successMessage = `${appName} version ${appVersion}`;
                if (!!_appVersionEl) {
                    _appVersionEl.classList.remove(errorClass);
                    _appVersionEl.innerHTML = _successMessage;
                }
            } else {
                if (!!_appVersionEl) {
                    _appVersionEl.classList.add(errorClass);
                    _appVersionEl.innerHTML = `Error: While fetching sample project version.`;
                }
            }
        });
    }

    /**
     * Display Crestron Component Library version information using
     * ch5-modal-dialog.
     */
    function versionInformation() {
        let _crComLibVersion = CrComLib.version;
        let _crComBuildDate = CrComLib.buildDate;
        let _versionEl = document.getElementById('versionDescription');
        if (!!_crComLibVersion && !!_crComBuildDate) {
            let _successMessage = `Crestron Component Library version ${_crComLibVersion} build date ${_crComBuildDate}`;
            if (!!_versionEl) {
                _versionEl.classList.remove(errorClass);
                _versionEl.innerHTML = _successMessage;
            }
        } else {
            if (!!_versionEl) {
                _versionEl.classList.add(errorClass);
                _versionEl.innerHTML = `Error: While fetching crestron component library version.`;
            }
        }
    }

    /**
     * Declare your Public Methods here
     */
    function getOutput() {
        return outputValue;
    }

    /**
     * All public or private methods which need to call onInit
     */
    // Once the component is added to the view, then the below lines can be uncommented.
    // let versionInfoPage = document.querySelector('#version-info-page');
    // versionInfoPage.addEventListener('afterLoad', onInit);
    document.addEventListener('DOMContentLoaded', onInit);

    /**
     * All public method and properties are exported here
     */
    return {
        getOutput: getOutput
    };

}());